### ISSUE TITLE
Dagre布局存在的缺陷以及解决方法

### ISSUE THREAD

**Issue by lemon0818** [antvis/layout#103]
**两节点双向指向时导致layoutLabel不存在**
当A节点和B节点存在双向连接时，会存在第二条双向连接线报错情况
@antv\layout\es\layout\dagre\src\layout.js内部的updateInputGraph方法中
<img width="854" alt="1667554678284" src="https://user-images.githubusercontent.com/84186015/199941242-e137ab1a-2736-48ea-928b-e525ed542333.png">
此处是否需要做出判断进行修正处理
![image](https://user-images.githubusercontent.com/84186015/199941742-008bd09c-a227-48a8-aa92-4e37815dfc4a.png)

**Comment by lemon0818** [comment]
<img width="788" alt="1667555128345" src="https://user-images.githubusercontent.com/84186015/199942862-abf9b9f4-16ee-4575-8126-0d22e0575e22.png">
根据官网文档，仅存在起点的 layer 一定小于终点的 layer 值，同layer双向连接情况是否考虑缺失？
本地版本
<img width="238" alt="1667555222162" src="https://user-images.githubusercontent.com/84186015/199943161-e4630dcc-1f96-4b1f-b8cf-8e32a6ea111f.png">

**Comment by Yanyan-Wang** [comment]
可以提 pr 看看～
